# Generated by Django 4.2.25 on 2025-11-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
