# Generated by Django 4.2.25 on 2025-12-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paypal_order_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
